Support schema definition for redshift
In addition to postgres, redshift database is also support schema.
Respect it by 'currentSchema' param.

Also, we need to not include this param as in in Django's DATABASES
settings. Otherwise, following error is raised:

```
django.db.utils.OperationalError: invalid connection option
"currentSchema"
```